config/routes.rb
Whisper::Application.routes.draw do
  root :to => "home#index"

  match "/blog" => "entries#index"
  match "/blog/feed" => "entries#feed", :as => :feed, :defaults => { :format => "atom" }

  match "/6th" => "home#six", :as => :six

  match "/article/:permalink" => "entries#show", :as => :entry_show
  match "/article/edit/:permalink" => "entries#edit", :as => :entry_edit
  match "/entry/search" => "entries#search", :as => :entry_search

  match "/login" => "sessions#new"
  match "/logout" => "sessions#destroy"
  match "/session" => "sessions#create", :as => :session, :via => [:post]

  match "/entry/new" => "entries#new", :as => :entry_new
  match "/entry/create" => "entries#create", :as => :entry, :via => [:post]

  match "/entry/update/:permalink" => "entries#update", :as => :entry_update, :via => [:put]
  match "/entry/destroy/:permalink" => "entries#destroy", :as => :entry_destroy, :via => [:delete]
end

app/models/entry.rb
class Entry
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Search

  field :title
  field :body

  field :permalink

  index :permalink, :unique => true

  validates :title, :presence => true
  validates :title, :length => { :in => 0..25 }

  validates :body, :presence => true
  validates :body, :length => { :minimum => 50 }

  validates :permalink, :uniqueness => true

  search_in :title, :body

  belongs_to :user

  before_validation :to_permalink

  def to_permalink
    self.permalink = self.title.gsub('/([[:punct:]]|\s)/', '-')
  end

  class << self
    def find_by_permalink(permalink)
      where(:permalink => permalink).try(:first)
    end
  end
end

app/models/invite_code.rb
class InviteCode
  include Mongoid::Document

  attr_accessible :code

  field :code
  field :valid, :type => Boolean, :default => true

  belongs_to :user

  def confirm
    self.valid = !self.valid
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps

  attr_accessible :username, :password, :password_confirmation
  attr_accessor :password

  auto_increment :number, :seed => 0

  field :username

  field :password_hash
  field :password_salt

  validates :username, :presence => true
  validates :username, :uniqueness => true
  validates :username, :length => { :in => 5..15 }

  validates :password, :confirmation => true
  validates :password, :length => { :in => 8..20 }

  before_save :encrypt_password

  has_many :entries, :dependent => :nullify

  def self.authenticate(username, password)
    user = where(:username => username).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end

  def self.find_by_number(number)
    where(:number => number).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user, :logged_in?

  private
    def current_user
      @current_user ||= User.find_by_number(session[:user_id]) if session[:user_id]
    end

    def logged_in?
      !!current_user
    end

    def require_login
      unless logged_in?
        redirect_to login_path, :notice => "You must be logged in!"
      end
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :require_login, :except => [:show, :search, :index, :feed]

  def index
    @entries = Entry.all
    @date = (params[:year] || params[:month]) ? Date.parse(params[:year] || params[:month]) : Date.today

    @blog = 1
  end

  def new
    @entry = Entry.new
  end

  def show
    @entry = Entry.find_by_permalink(params[:permalink])

    @prev = Entry.only(:permalink, :created_at).where(:created_at.lt => @entry.created_at).asc(:created_at).last
    @next = Entry.only(:permalink, :created_at).where(:created_at.gt => @entry.created_at).asc(:created_at).first
  end

  def edit
    @entry = Entry.find_by_permalink(params[:permalink])
  end

  def create
    @entry = current_user.entries.create(params[:entry])

    if @entry.save
      redirect_to entry_show_path(@entry.permalink), :notice => "Successfully created!"
    else
      flash[:alert] = "Fail"
    end
  end

  def update
    @entry = Entry.find_by_permalink(params[:permalink])
    @entry.update_attributes(params[:entry])

    if @entry.save
      redirect_to entry_show_path(@entry.permalink), :notice => "Successfully created!"
    else
      flash[:alert] = "Fail"
    end
  end

  def destroy
    @entry = Entry.find(params[:id])

    if @entry.destroy
      respond_to do |format|
        format.js
      end
    else
      respond_to do |format|
        format.js { render "shared/fail_to_destroy" }
      end
    end
  end

  def search
    @entries = Entry.search(params[:keyword])
  end

  def feed
    @entries = Entry.all

    respond_to do |format|
      format.atom
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @index = 1
  end

  def six
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_filter :require_login, :except => [:new, :create]

  def new
  end

  def create
    user = User.authenticate(params[:username], params[:password])

    if user
      session[:user_id] = user.number
      redirect_to blog_path, :notice => "Logged in!"
    else
      redirect_to login_path, :notice => "Invalid username or password!"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to blog_path, :notice => "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #def new
  #  @user = User.new
  #  @invite_code = params[:invite_code]
  #end

  #def invite
  #  invite_code = InviteCode.where(:code => params[:invite_code]).first
  #
  #  if invite_code
  #    #redirect_to new_path(params[:invite_code])
  #  end
  #end

  #def create
  #  @invite_code = params[:user][:invite_code]
  #  @id = InviteCode.where(:code => @invite_code).first
  #
  #  #@user = User.create!()
  #end

  #def destroy
  #
  #end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def coderay(content)
    defaults = {
      :css => :class,
      :line_numbers => :inline,
      :tab_width => 2
    }

    content.gsub(/\<pre\>\<code class=\"(.+?)\"\>(.+?)\<\/code\>\<\/pre\>/m) do
      d = $2
      CodeRay.scan(unescape(d), $1).div(defaults)
    end
  end

  def markdown(text)
    options = {
        :hard_wrap => true,
        :autolink => true,
        :no_intra_emphasis => true,
        :fenced_code_blocks => true,
        :space_after_headers => true,
        :strikethough => true,
        :superscript => true
    }

    renderer = Redcarpet::Markdown.new(Redcarpet::Render::HTML, options)
    coderay(renderer.render(text)).html_safe
  end

  def unescape(content) # :nodoc:
    # use gsub in case nil is returned
    content.gsub(/(&quot;|&#39;|&amp;|&lt;|&gt;)/) do
      case $1
        when "&quot;"
          '"'
        when "&#39;"
          "'"
        when "&amp;"
          "&"
        when "&lt;"
          "<"
        when "&gt;"
          ">"
      end
    end
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/_form.html.erb
<%= form_for @entry, :url => url, :method => method,:validate => true do |f| %>
  <p><%= f.text_field :title, :placeholder => "Titile" %></p>
  <p><%= f.text_area :body, :placeholder => "Content"%></p>
  <%= f.submit :submit %>
<% end %>

app/views/entries/edit.html.erb
<%=stylesheet_link_tag "publish" %>

<div id="publish">
  <%= render :partial => "form", :locals => { :url => :entry_update, :method => :put } %>
</div>

app/views/entries/index.html.erb
<%=stylesheet_link_tag "blog" %>

<div id="calendar">
  <div id="date">
    <div id="middle">
      <div id="left-year"><%= link_to "<", :year => (@date.prev_year).strftime("%Y-%m-%d") %></div>
      <div id="left-month"><%= link_to "<", :month => (@date.prev_month).strftime("%Y-%m-%d") %></div>
      <%=h @date.strftime("%b %Y") %>
      <div id="right-month"><%= link_to ">", :month => (@date.next_month).strftime("%Y-%m-%d") %></div>
      <div id="right-year"><%= link_to ">", :year => (@date.next_year).strftime("%Y-%m-%d") %></div>
    </div>
  </div>
  <%= calendar_for @entries, :year => @date.year, :month => @date.month do |calendar| %>
    <%= calendar.head('Sun.', 'Mon.', 'Tue.', 'Wed.', 'Thu.', 'Fri.', 'Sat.') %>
    <% calendar.day(:day_method => :created_at) do |date, entries| %>
        <%= date.day %>
        <ul>
        <% for entry in entries %>
            <li><%= link_to h(entry.title), entry_show_path(entry.permalink) %></li>
        <% end %>
        </ul>
    <% end %>
  <% end %>
</div>

<%= javascript_include_tag "blog" %>

app/views/entries/new.html.erb
<%=stylesheet_link_tag "publish" %>

<div id="publish">
  <%= render :partial => "form", :locals => { :url => :entry, :method => :post } %>
</div>

app/views/entries/search.html.erb
<%= stylesheet_link_tag "search" %>

<div id="results">
  <% if @entries.blank? %>
    <p>No results!</p>
  <% else %>
    <% @entries.each do |entry| %>
      <p><%= link_to "#{entry.title}", entry_show_path(entry.permalink) %></p>
    <% end %>
  <% end %>
</div>

app/views/entries/show.html.erb
<%= stylesheet_link_tag "show" %>

<div class="entry" id="top">
  <div class="left">
    <% if @prev %>
      <%= link_to '<div id="prev"></div>'.html_safe, entry_show_path(@prev.permalink) %>
    <% else %>
      <div id="prev"></div>
    <% end %>

  </div>

  <div class="details">
    <div class="title">
        <h2>
          <%= @entry.title %>
          <% if logged_in? %>
            <span>
              <%= link_to "Edit", entry_edit_path(@entry.permalink) %>
              <%= link_to "Destroy", entry_destroy_path(@entry.permalink), :confirm => "Sure?" %>
            </span>
          <% end %>
        </h2>
        <div id="help">
          <div id="help-popup">
            <b>Please use Chrome 17+, IE 9.0+ or Firefox 4.0+</b>
            <p>Top right corner for meta info.</p>
            <p>Bottom right corner for goting back and top.</p>
            <p>Left and right arrows for prev and next article.</p>
          </div>
        </div>
        <div id="info">
          <div id="info-popup">
            <p>Author: <%= @entry.user.username %></p>
            <p>Published at: <%= @entry.created_at.strftime("%F %T %Z") %></p>
            <p>Updated at: <%= @entry.updated_at.strftime("%F %T %Z") %></p>
          </div>
        </div>
        <div id="search">
        </div>

        <div id="search-popup">
          <%= form_tag entry_search_path do %>
            <%= text_field_tag :keyword, nil, :placeholder => "Keyword" %>
            <%= submit_tag :Go %>
          <% end %>
        </div>
    </div>

    <div class="body">
        <%= markdown(@entry.body) %>
        <div id="gotop"></div>
        <%= link_to '<div id="goback"></div>'.html_safe, blog_path %>
    </div>
  </div>

  <div class="right">
    <% if @next %>
        <%= link_to '<div id="next"></div>'.html_safe, entry_show_path(@next.permalink) %>
    <% else %>
        <div id="next"></div>
    <% end %>
  </div>
</div>

<div id="disqus_thread"></div>
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
    var disqus_shortname = 'lastomato'; // required: replace example with your forum shortname

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

<%= javascript_include_tag "entry_show" %>

<% unless @prev %>
  <script type="text/javascript">
    window["prev"].remove();

    $("div#prev").css('cursor', 'auto');
  </script>
<% end %>

<% unless @next %>
  <script type="text/javascript">
    window["next"].remove();

    $("div#next").css('cursor', 'auto');
  </script>
<% end %>

app/views/home/index.html.erb
<%=stylesheet_link_tag "whisper" %>

<div id="index" xmlns="http://www.w3.org/1999/html">
  <p>Jie Fan <span>A.K.A Tomato</span></p>

  <%= link_to '<div id="blog"></div>'.html_safe, blog_path %>
  <%= link_to '<div id="github"></div>'.html_safe, "https://www.github.com/lastomato" %>
  <%= link_to '<div id="mail"></div>'.html_safe, "mailto:ustc.flyingfox@gmail.com" %>
  <%= link_to '<div id="twitter"></div>'.html_safe, "https://www.twitter.com/lastomato" %>
  <%= link_to '<div id="renren"></div>'.html_safe, "http://www.renren.com/lastomato" %>
</div>

<%= javascript_include_tag "index" %>

app/views/home/six.html.erb
<%= stylesheet_link_tag "six" %>

<div id="time">
  <div id="year"></div>
  <div id="month"></div>
  <div id="day"></div>
  <div id="hour"></div>
  <div id="minute"></div>
  <div id="second"></div>
</div>

<%= javascript_include_tag "six" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= "Whisper" %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if logged_in? && @blog %>
  <div id="nav">
    <div id="inner">
      <ul>
        <li><%= link_to "Index", root_path %></li>
        <li><%= link_to "Post", entry_new_path %></li>
        <li><%= link_to "Logout", logout_path %></li>
      </ul>
    </div>
  </div>
<% end %>

<div class="container">
  <%= yield %>
</div>

<% unless @index %>
    <div id="footer">
    <hr />
      <p>&copy; <span>Tomato</span> 2012. Proudly powered by <%= link_to "whisper", "https://github.com/lastomato/whisper" %></p>
    </div>
<% end %>

</body>
</html>